### ISSUE TITLE
为什么要 `declare var Int64`？

### ISSUE THREAD

**Issue by Axure** [LPegasus/dts-from-thrift#11]
这里：https://github.com/LPegasus/dts-from-thrift/blob/58c66f8c80228ce9d81b7b73850afeda0d5f7442/src/tools/tsHelper.ts#L1-L4

实际上并不能保证有一个 `Int64` 的类被注入。不生成这一段似乎也没有什么影响。

生成这样的文件，是否会误导使用者将 `Int64` 作为一个类使用呢？

**Comment by LPegasus** [comment]
出发点只是让 number 和 string 都能赋值给 Int64 类型。具体如何处理 Int64，每个业务的实现应该不一样的。需要根据实际情况修改。
